name: NBookStorage
description: A tool to save books as yaml files.
website: https://github.com/yueyinqiu/NBookStorage/wiki
api-version: '1.13'

version: '1.11'
author: yueyinqiu5990
main: top.nololiyt.bookstorage.RootPlugin

commands:
  nbookstorage:
    description: "All commands for the plugin 'NBookStorage'."
    aliases: [nbs,books,nbooks,bookstorage]